SELECT * FROM "tag_categories";
SELECT * FROM "tags";
SELECT * FROM "projects";
SELECT * FROM "project_tags";
SELECT * FROM "about";
SELECT * FROM "social_media";
SELECT * FROM "experience";
SELECT * FROM "experience_tags";
SELECT * FROM "contact_messages";